In [9]:
import tensorflow as tf
tf.InteractiveSession()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [26]:
x = tf.range(0,6)
a = tf.reshape(x, [3, 2])
# b = tf.transpose(x, perm=[1,0])
print(a.eval())

[[0 1]
 [2 3]
 [4 5]]


In [27]:
x = tf.random.uniform((2,3,4,6))
y = tf.random.uniform((2,3,6,1))
z = tf.matmul(x,y)
z.eval().shape

(2, 3, 4, 1)

In [32]:
x = tf.range(0,12)
y = tf.reshape(x, [1,3,4])
z = tf.reverse_sequence(y, [3], batch_axis=0, seq_axis=1)
print(y.eval())
print(z.eval())

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[ 8  9 10 11]
  [ 4  5  6  7]
  [ 0  1  2  3]]]


In [35]:
# x = tf.range(0,12).reshape((3,4))
x = tf.reshape(tf.range(0,12), (3,4))
y = tf.reshape(tf.range(0,12), (3,4))
z = x * y
print(z.eval())

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [39]:
x = tf.random.uniform([1,2,700,700])
y = tf.random.uniform([1,1,1,700])

In [40]:
x * y

<tf.Tensor 'mul_2:0' shape=(1, 2, 700, 700) dtype=float32>

In [3]:
indices = [0, 1, 2, 3]
depth = 3
tf.one_hot(indices, depth).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)

In [4]:
tf.get_variable(9)

ValueError: The initializer passed is not valid. It should be a callable with no arguments and the shape should not be provided or an instance of `tf.keras.initializers.*' and `shape` should be fully defined.

In [4]:
for i in range(10):
    print(i)

    if i == 9:
        print("Too big - I'm giving up!")
        break;
else:
    print("Completed successfully")

0
1
2
3
4
5
6
7
8
9
Too big - I'm giving up!


In [5]:
a = {'a': 5}
b = a

In [7]:
a.update({'b': 6})

In [8]:
b

{'a': 5, 'b': 6}

In [19]:
x = tf.random.uniform((5,6,7))
y = tf.layers.dense(x, 512)

In [21]:
# y.eval()#.shape
# y.shape

In [5]:
x = tf.constant([[False,  False], [False, False]])
tf.reduce_any(x).eval()

False

In [7]:
x = tf.random.uniform((32,500,128))
y = tf.random.uniform((32,500,1))
x * y

<tf.Tensor 'mul:0' shape=(32, 500, 128) dtype=float32>

In [21]:
tf.reset_default_graph()
x = tf.random.uniform((32,500,128))

y = tf.layers.separable_conv1d(
    x, 
    128, 
    30,
    strides=1,
    padding="same",
    name="seperable_conv1d",
    activation=tf.nn.relu
)

In [22]:
y.shape

TensorShape([Dimension(32), Dimension(500), Dimension(128)])